### ISSUE TITLE
API_ID_INVALID

### ISSUE THREAD

**Issue by goodmind** [goodmind/telegram.link#11]
error with `auth.sendCode`, lol why

**Comment by goodmind** [comment]
fixed by https://github.com/goodmind/telegram-tl-node/commit/6413eb525d1839edc5ed3c04b44bf00d34c521fd

**Comment by shaurgon** [comment]
via [Telecommander](https://github.com/fazo96/telecommander):
```
TELEGRAM.LINK
v.0.6.5

Connecting...
Downloading Authorization Key...
Checking your phone number with Telegram...
Errors: 400 API_ID_INVALID
```

**Comment by goodmind** [comment]
@shaurgon why you posting this here?

**Comment by goodmind** [comment]
@shaurgon Telecommander is don't maintained, sorry

**Comment by shaurgon** [comment]
@goodmind because is using telegram.link for connections and error listed from telegram.link  =)
I fix it some time ago, thanks for maintain dead project!
