### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by mzilot** [goodmind/telegram.link#13]
Hi,
I'm giving below logs and pause working when call every api method after auth such as sendCode and getDatacenters.

    [INFO] Tue, 10 Jan 2017 21:43:53 GMT  net.EncryptedRpcChannel Call of 'mtproto.service.invokeWithLayer' took 206ms
    [INFO] Tue, 10 Jan 2017 21:43:53 GMT  net.EncryptedRpcChannel New session has been created by Telegram: { T:mtproto.type.New_session_created, first_msg_id: "0x58755599045a1c74", unique_id: "0xc502126bcf63a3aa", server_salt: "0xc63ac5a8349d52c7" }
    [INFO] Tue, 10 Jan 2017 21:43:53 GMT  net.EncryptedRpcChannel Send the ack to the server: { T:mtproto.type.Msgs_ack, msg_ids: { T:Vector, type: "Long", list: ["0x5875559932ad5001"] } }
    [INFO] Tue, 10 Jan 2017 21:43:53 GMT  net.EncryptedRpcChannel The server sent a acknowledge for the followings [0x58755599045a1c74]

**Comment by goodmind** [comment]
How you authenticate?

**Comment by mzilot** [comment]
I had set the app.connectionType to TCP, now i change it to HTTP or nothing and it works properly.

**Comment by goodmind** [comment]
I think that there is some bug in TCP transport (I didn't touch mt-node, only fixed schema parser)

**Comment by leonerd** [comment]
I've been running into this exact same issue. It just pauses there, never continuing.

If I switch to HTTP transport instead, then it still fails but I get a different kind of failure.

Over HTTP, I can make the initial call to `auth.sendCode()` on the first data centre, receive a redirection result that sends me in the direction of a different one, and connect to that instead. But then I'm get lots of

    [ERROR] Thu, 12 Jan 2017 19:06:22 GMT  net.RpcChannel Unable to read: <html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/0.3.33</center>
    </body>
    </html>

And an eventual

    [WARN] Thu, 12 Jan 2017 19:06:32 GMT  get-flow.retryUntilIsDone Fail, retries limit = 10 has been reached!
