### ISSUE TITLE
Phone migrate error

### ISSUE THREAD

**Issue by mzilot** [goodmind/telegram.link#14]
When i try to call `sendCode`, it return `303` error with message that i should `migrate phone` to data center 4 : DC_4
Next step, i receive `Error: Nonce mismatch` when i try to create new client with DC_4

    [ERROR] Wed, 11 Jan 2017 22:26:24 GMT  net.HttpConnection Error ENETUNREACH
    [ERROR] Wed, 11 Jan 2017 22:26:24 GMT  net.RpcChannel Unable to read: Error: connect ENETUNREACH 2001:0b28:f23f:f005:0000:0000:0000:000a:443 
    [ERROR] Wed, 11 Jan 2017 22:26:24 GMT  get-flow.runSeries Exception occurs: Error: Nonce mismatch.
        at createError (/home/mlk/projects/telegramity/node_modules/@goodmind/telegram.link/node_modules/@goodmind/telegram-mt-node/lib/auth/request-pq.js:88:17)
    at callback (/home/mlk/projects/telegramity/node_modules/@goodmind/telegram.link/node_modules/@goodmind/telegram-mt-node/lib/auth/request-pq.js:42:26)
    ....
It seems it can't connect to DC_4.
Do you have a test application like termgram to test your forked telegram.link?
@goodmind

**Comment by goodmind** [comment]
Yes, I have termgram, but some datacenters IPs now returned as IPv6 and TCP or HTTP can't connect

**Comment by mzilot** [comment]
The `telegram.link` return IPv4 IPs of data centers when it call getDatacenters, but `@goodmind/telegram.link` return IPs as IPv6!
Can you use your `@goodmind/telegram.link` module in `termgram` instead of master `telegram.link` module?

**Comment by goodmind** [comment]
This is because schema is 57. You can, just change `telegram.link` in requires to `@goodmind/telegram.link`

**Comment by mzilot** [comment]
I need to solve this issues and run correctly. Shall you help me to solve it?

**Comment by goodmind** [comment]
If your provider supports ipv6 then it maybe will works :)

**Comment by mzilot** [comment]
Shall you develop and support this project?
I can define this as project in freelancer.com

**Comment by goodmind** [comment]
Are you talking about supporting termgram?
