### ISSUE TITLE
HTML-level errors from `auth.sendCode`

### ISSUE THREAD

**Issue by leonerd** [goodmind/telegram.link#16]
I get no response at all attempting to use `auth.sendCode` over TCP (see #13), so I'm trying HTTP instead.

I successfully make an initial request to `auth.sendCode` and receive a `PHONE_MIGRATE_4` error. I migrate to DC4 and try again, and this time get stuck in a loop:

```
[DEBUG] Thu, 12 Jan 2017 19:27:54 GMT  net.HttpConnection add buffer(340) to the write buffer queue, total length 340 +0ms
[DEBUG] Thu, 12 Jan 2017 19:27:54 GMT  net.HttpConnection content-length = 340
  net.HttpConnection content-type = undefined
  net.HttpConnection accept = undefined
  net.HttpConnection host = 149.154.165.120:443
  net.HttpConnection connection = keep-alive
  net.HttpConnection  +2ms
[DEBUG] Thu, 12 Jan 2017 19:27:54 GMT  net.HttpConnection writing request(340) to {"withCredentials":false,"path":"/apiw1","port":443,"host":"149.154.165.120","protocol":"http:"} +0ms
[DEBUG] Thu, 12 Jan 2017 19:27:54 GMT  net.HttpConnection reading from {"withCredentials":false,"path":"/apiw1","port":443,"host":"149.154.165.120","protocol":"http:"}
  net.HttpConnection status: 404
  net.HttpConnection headers: {"server":"nginx/0.3.33","date":"Thu, 12 Jan 2017 19:27:54 GMT","content-type":"text/html","connection":"close","access-control-allow-origin":"*","access-control-allow-methods":"POST, OPTIONS","access-control-allow-headers":"origin, content-type","access-control-max-age":"1728000","content-length":"169"} +38ms
[ERROR] Thu, 12 Jan 2017 19:27:54 GMT  net.RpcChannel Unable to read: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/0.3.33</center>
</body>
</html>
 
[ERROR] Thu, 12 Jan 2017 19:27:54 GMT  auth.RequestDHParams <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/0.3.33</center>
</body>
</html>

[ERROR] Thu, 12 Jan 2017 19:27:54 GMT  get-flow.runSeries Exception occurs: undefined
[ERROR] Thu, 12 Jan 2017 19:27:54 GMT  get-flow.runSeries Exception occurs: undefined
```

Eventually this will fail, the value result of the failure itself being the actual HTTP string here, containing this nginx 404 error HTML code.

**Comment by goodmind** [comment]
I only tested DC_2, how are you connecting (creating client)?

**Comment by leonerd** [comment]
In summary: the code lives here - https://github.com/matrix-org/matrix-appservice-tg/blob/master/lib/TelegramGhost.js

More specifically, I create the client at https://github.com/matrix-org/matrix-appservice-tg/blob/master/lib/TelegramGhost.js#L87

I then call `auth.sendCode` on it at https://github.com/matrix-org/matrix-appservice-tg/blob/master/lib/TelegramGhost.js#L160 via https://github.com/matrix-org/matrix-appservice-tg/blob/master/lib/TelegramGhost.js#L125

The first call on this on the primary DC returns a `PHONE_MIGRATE_4` error, handled at https://github.com/matrix-org/matrix-appservice-tg/blob/master/lib/TelegramGhost.js#L129 and reconnects to the next DC.

It's at this point where `auth.sendCode` is called again by theabove code on a different client, and runs into those 404 errors, never making further progress.

The code linked above has been tested and works fine against the upstream @enricostara version of `telegram.link`, but using that has turned out unsatisfactory because it only exposes layer 23, and I want the newer features available in layer 57, hence using yours.

**Comment by goodmind** [comment]
@leonerd telegram returning wrong IPs (maybe)

In webogram there is just hardcoded IPs
```js
[
{id: 1, host: '149.154.175.50', port: 80},
{id: 2, host: '149.154.167.51', port: 80},
{id: 3, host: '149.154.175.100', port: 80},
{id: 4, host: '149.154.167.91', port: 80},
{id: 5, host: '149.154.171.5', port: 80} 
]
```
 and `DC_4` ip is different from what returned from `help.getConfig`
I don't tested it but I think they're also works with `443` port

**Comment by leonerd** [comment]
> {id: 4, host: '149.154.167.91', port: 80},

As compared my code, which tried

>   net.HttpConnection host = 149.154.165.120:443

Wow that is quite the difference. I'll try tomorrow hardcoding that above list into my code and see if it makes a difference.

**Comment by leonerd** [comment]
Well, this was certainly Interesting. The result I get asking Telegram directly is:

    DC_1: 
     { host: '2001:0b28:f23d:f001:0000:0000:0000:000a',
       port: 443 },
    DC_2: 
     { host: '2001:067c:04e8:f002:0000:0000:0000:000a',
       port: 443 },
    DC_3: 
     { host: '2001:0b28:f23d:f003:0000:0000:0000:000a',
       port: 443 },
    DC_4: 
     { host: '149.154.165.120',
       port: 443 },
    DC_5: 
     { host: '2001:0b28:f23f:f005:0000:0000:0000:000a',
       port: 443 },

So... four IPv6 addresses I can't even use from my hosting location, and one incorrect IPv4.
I think I can see now why everyone hardcodes this in their client libraries.

Oh Telegram.. :/

**Comment by leonerd** [comment]
Yep, that did it.

Now works if I hardcode those values in - https://github.com/matrix-org/matrix-appservice-tg/commit/6b4ee9ded3e8f974eb5d3c1a23cee60b1fdbb7ed

**Comment by goodmind** [comment]
Yea I think I should make boolean parameter in `getDataCenters` to return hardcoded servers

**Comment by leonerd** [comment]
Yes, that could be a solution. Or even make that the default option really, or something. If I didn't know about that problem I'd have stumbled on it for ages.

Is there any way we can contact Telegram about it, to have their actual servers not lie in the response? It seems stupid to have to workaround it in this manner.

**Comment by goodmind** [comment]
> Is there any way we can contact Telegram about it, to have their actual servers not lie in the response? It seems stupid to have to workaround it in this manner.

I think no :)

**Comment by leonerd** [comment]
Shall I close this issue now - from my perspective, the hardcoding workaround is enough to get my code working. Or do you still want it open to track the hardcoding-option feature?

**Comment by goodmind** [comment]
check out #17

**Comment by leonerd** [comment]
This seems to be fixed by #17 now.

**Comment by arcanjoqt** [comment]
All of those 404 that I was receiving at the time (not only sendCode) were caused by this [GET](https://github.com/goodmind/telegram-mt-node/blob/master/lib/net/http-connection.js#L72)
because I was sending nothing to Telegram. Some other call was deleting all the the contents to be sent, so I tested changing [this line](https://github.com/goodmind/telegram-mt-node/blob/master/lib/net/rpc-channel.js#L69) to get a new connection every time end those 404 errors seems to be gone.

**Comment by goodmind** [comment]
I'm not sure about this, because primarily 404s are because findPQ is calculating wrong buffers:

https://github.com/goodmind/telegram-mt-node/blob/master/lib/auth/request-pq.js#L58-L59

**Comment by goodmind** [comment]
This is really annoying bug which prevents us connecting to multiple datacenters in [treact](https://github.com/goodmind/treact) which uses @zerobias's [telegram-mtproto](https://github.com/zerobias/telegram-mtproto)

So @zerobias decided to rewrite webogram completely instead of using this library :)

**Comment by leonerd** [comment]
What's the current status of this issue? I'm once again running into 404 errors, this time due to all kinds of API calls. I'm using the hardcoded DC IP addresses option.

**Comment by leonerd** [comment]
Having dug into this a little more, I think there's either a race condition or something else similarly unreliable going on here.

By making no changes to code or data and just repeating the attempt, I can get either of three outcomes: HTML-level 404 error, an ENONCE error, or success. I wonder if there's something strange going on with multiple requests in-flight colliding with each other.

**Comment by goodmind** [comment]
@leonerd what is your telegram username?

**Comment by leonerd** [comment]
@goodmind - `@leonerduk`
