### ISSUE TITLE
HTTP transport sometimes stalls but is resumable

### ISSUE THREAD

**Issue by leonerd** [goodmind/telegram.link#19]
Sometimes (maybe about 50% of the time?) a call to an API method over the HTTP API just stalls. It doesn't fail, but doesn't succeed either. If I send another command (of the same or different type) that's usually sufficient to wake it up and then I receive both responses.

By watching another telegram client on my phone, it appears that the command itself does get executed (e.g. if it's a `messages.sendMessage()` call then the message does appear on Telegram); it seems purely related to reading back of responses from the server. It feels like something temporarily stops trying to receive responses from the server.

**Comment by goodmind** [comment]
There is many of setIntervals and setTimeouts in `telegram-mt-node` and I don't completely understand how this works :(

**Comment by leonerd** [comment]
Ah; I believe this is basically "programmer error".

The HTTP transport needs some help getting timely replies back from the telegram server, which requires you to call

    client.startHttpPollLoop()

Having done that, it now seems nicely reliable.
