### ISSUE TITLE
Wrap some of the `channels` API calls

### ISSUE THREAD

**Issue by leonerd** [goodmind/telegram.link#20]
I shall be needing quite a few of the functions in the `channels` namespace. I see they're not yet wrapped.

I'll probably have a go at implementing this locally, and if I get to a point where I have something that seems useful I'll send a PR

**Comment by goodmind** [comment]
Thank you for contributing!

**Comment by leonerd** [comment]
I have made a start on this branch. https://github.com/leonerd/telegram.link/tree/leonerd/channels

I'll keep adding to it for a while before I make a PR to bring in all the bits of API that I seem to need.

**Comment by goodmind** [comment]
You can just iterate through `Object.keys(api.service.channels)` and add methods dynamically or write to file
