### ISSUE TITLE
Constant accumulation of "updates"

### ISSUE THREAD

**Issue by leonerd** [goodmind/telegram.link#22]
I'm as yet unsure whether this is me doing something wrong, or a real bug in the library, but reporting it here anyway:

I've started attempting to handle incoming "updates", by using the `client.registerOnUpdates()` method, and calling `client.updates.getState()`. After I do that, I find that I receive an update in due course from Telegram. But then I receive two - the original and another one. And then three - those first two, plus one more. Each time I receive an update I also receive all the prior ones too.

For example:

    [INFO] Tue, 17 Jan 2017 19:54:44 GMT  net.EncryptedRpcChannel Call of 'mtproto.type.Msgs_ack' took 5820ms
    UPDATE: user status user_id=1234 _t=api.type.UserStatusOffline
    [INFO] Tue, 17 Jan 2017 19:54:44 GMT  net.EncryptedRpcChannel Call of 'mtproto.service.invokeAfterMsg' took 6595ms
    UPDATE: user status user_id=1234 _t=api.type.UserStatusOffline
    UPDATE: user status user_id=5678 _t=api.type.UserStatusOnline
    [INFO] Tue, 17 Jan 2017 19:54:45 GMT  net.EncryptedRpcChannel Call of 'mtproto.service.http_wait' took 7569ms
    UPDATE: user status user_id=1234 _t=api.type.UserStatusOffline
    UPDATE: user status user_id=5678 _t=api.type.UserStatusOnline
    UPDATE: user status user_id=1234 _t=api.type.UserStatusOnline
    [INFO] Tue, 17 Jan 2017 19:54:46 GMT  net.EncryptedRpcChannel Call of 'mtproto.service.http_wait' took 367ms
    UPDATE: user status user_id=1234 _t=api.type.UserStatusOffline
    UPDATE: user status user_id=5678 _t=api.type.UserStatusOnline
    UPDATE: user status user_id=1234 _t=api.type.UserStatusOnline
    UPDATE: user status user_id=5678 _t=api.type.UserStatusOffline

I can think of two possibilities here:
  1) The Telegram server requires some sort of explicit acknowledgement of each update to stop it sending them again, or
  2) The `telegram.link` library is buffering them locally and finding them all over and over again.

If I simply quit and restart my program, then the updates start again from scratch - I never seem to see those updates previously received. Plus by looking at some code of other telegram clients, I don't see any sort of "server acknowledge" mechanism to tell the server we've received those messages, so I begin to suspect the second possibility; that somehow these messages are all remaining inside the local client and being found again and again each time one new one is received.

Does that sound plausible? If so any idea where I might begin looking for it?

**Comment by leonerd** [comment]
Weird. It does for all the world look like these updates really are coming from Telegram.

Having added a line into `telegram-mt-node/lib/net/http-connection.js`:

                 var data = Buffer.concat(buffers);
    +            console.log(">>> net.http-connection received a total of " + data.length + " bytes");

Then I see in my log:

    >>> net.http-connection received a total of 88 bytes
    >>> net.http-connection received a total of 152 bytes
    >>> net.http-connection received a total of 184 bytes
    >>> net.http-connection received a total of 264 bytes
    >>> net.http-connection received a total of 312 bytes
    >>> net.http-connection received a total of 344 bytes
    >>> net.http-connection received a total of 392 bytes
    >>> net.http-connection received a total of 424 bytes
    >>> net.http-connection received a total of 472 bytes
    >>> net.http-connection received a total of 504 bytes

Those bytes really are coming from Telegram over and over again.

**Comment by goodmind** [comment]
I think that this pull request is related https://github.com/goodmind/telegram.link/pull/9

**Comment by leonerd** [comment]
That looks like it might have something to do with it. Do you have any idea how to actually use it though? What is the value of the `max_id` parameter I need to pass in? Some of the received updates have only a `date` field; some only a `pts`. I gather those are different message streams.

**Comment by leonerd** [comment]
Ah; this seems to be one of that most rare of Telegram APIs that *is* documented.

https://core.telegram.org/method/messages.receivedMessages

The docs here seem to quite clearly imply this is related to the PUSH notifications, as documented in https://core.telegram.org/api/push-updates rather than the regular "updates" mechanism

**Comment by goodmind** [comment]
Maybe you should try this https://core.telegram.org/method/updates.getDifference

**Comment by leonerd** [comment]
Aha! I have found it.

`EncryptedRpcChannel` is responsible for sending message ACKs back to Telegram. It does itself on receipt of the types of message it knows about; e.g. https://github.com/goodmind/telegram-mt-node/blob/7b1188ca7032fe80f81016e99cc3a44bd50f66ee/lib/net/encrypted-rpc-channel.js#L62-L63 handles this for inbound RPC results.

If you hook in new handlers for new message types (as the toplevel `Client.prototype.registerOnUpdates` does) this creates a new handler right at the parser level. Such a handler function would have to be responsible for sending its own ACKs.

I can currently hack this in to my own code by adding the lines

    // Horrible hack
    var channel = this._client._channel;
    channel._messageIdsToBeAck.push(updates._messageId);
    channel.sendMessagesAck();

into my "update" handler function. However this feels quite hacky - that should be handled by the library lower down, at some place or other.

**Comment by leonerd** [comment]
Actually; I'm not sure this is sufficient.

I no longer get yet more and more "updates" being called each time, but yet the number of bytes being transferred over HTTP is continuing to increase with each request. This confirmed by watching bytes over `tcpdump` - every roundtrip request is getting more and more bytes each time.

**Comment by leonerd** [comment]
By putting in more debugging prints, I believe what's happening is that every time a message whose toplevel type is "mtproto.type.Gzip_packed" is received, nothing exists that would ACK its message ID number, so these accumulate. E.g. I now have a constant stream of

    Messages:
      <Message id=0x587fa7855c700001 seq=37 body.type=mtproto.type.Gzip_packed
      <Message id=0x587fa7a61a0f4c01 seq=57 body.type=mtproto.type.Gzip_packed
      <Message id=0x587fa7a711566801 seq=59 body.type=mtproto.type.Gzip_packed

arriving along with every new update.

I suspect the entire structure of using parser side-effects to handle toplevel incoming messages is the mistake here. Maybe a more reliable structure would be to take the message IDs out of the toplevel object, whatever its type, and ACK it there?

**Comment by leonerd** [comment]
https://github.com/goodmind/telegram-mt-node/issues/12 solves this one entirely. It means my update handler logic doesn't need to be aware of message acks at all.
