### ISSUE TITLE
Updates contained in Gzipped messages aren't emitted

### ISSUE THREAD

**Issue by leonerd** [goodmind/telegram.link#23]
If I receive update-style messages from Telegram in the body of a `Gzip_packed` message, those don't hit the event emitted.

I believe this is because in EncryptedRpcChannel, `this._parser.parse()` is not invoked a second time on such a body.

I don't know the correct solution to this; I can see two possible ideas:

1. Extend the `parse` method in `message-parser.js` to unzip and walk into the contents of such a message.
2. Make a second call to `this._parser.parse` in `encrypted-rpc-channel.js` after unzipping.

**Comment by leonerd** [comment]
It's not terribly pretty but an attempt at option 2 appears at

https://github.com/goodmind/telegram-mt-node/compare/master...leonerd:leonerd/emit-from-gzip

Seems to solve the problem for me - I'm now receiving updates I wasn't before.

**Comment by goodmind** [comment]
When you get updates in gzipped container?

**Comment by leonerd** [comment]
Quite often. E.g. if there's a lot of text or a big media update with enough redundancy in its byte encoding, telegram sees fit to gzip that. I expect gzipping could happen at basically any time.
